# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '堆糖' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 堆糖
  pod 'SnapKit', '~> 0.22.0'
  pod 'SwiftyJSON', '~> 2.0’
  pod 'Alamofire', '~> 3.0'
  pod 'Kingfisher', '~> 2.0’
  pod 'MJRefresh'
  pod 'NVActivityIndicatorView', :git => 'https://github.com/ninjaprox/NVActivityIndicatorView.git', :branch => 'swift2.3'
  pod 'YYWebImage'

end
