# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '微博' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 0.15.0'
    pod 'Alamofire', '~> 3.0'
    pod 'Kingfisher', '~> 2.0'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']

end
