# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '日日煮' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'Masonry'
  # pod 'BlocksKit'
  # pod 'WMPageController'
  # pod 'CocoaLumberjack'
    pod 'MBProgressHUD'
  # pod 'TPKeyboardAvoiding'
  # pod 'MLTransition'
    pod 'FMDB'
  # pod 'CocoaAsyncSocket'
  # pod 'RESideMenu'
  # pod 'MWPhotoBrowser'
    pod 'YYKit'
    pod 'SDWebImage'
    pod 'UITableView+FDTemplateLayoutCell'
  # pod 'iCarousel'
  # pod 'PSCollectionView’

end
