# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '第三方框架' do
    # Uncomment this line to define a global platform for your project
    # platform :ios, '9.0'
    
        
        pod "AFNetworking"
        pod 'SDWebImage'
        pod 'MBProgressHUD'
        pod 'MJRefresh'
        pod 'MJExtension'
        pod 'SVProgressHUD'
        pod 'Masonry'
        pod 'SDCycleScrollView'
        

end
