# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '美团' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 美团

  target '美团Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '美团UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
