# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '微博(OC)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 微博(OC)

    pod 'MJRefresh'
    pod 'SVProgressHUD'
    pod 'SDWebImage'
    pod 'MJExtension'
    pod 'AFNetworking'
    pod 'MJPhotoBrowser'

end
