# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '百思不得姐' do
  
pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "Masonry"
# 动画
pod "pop"
# 扇形动画图
pod "DACircularProgress"
# 进度条
pod "M13ProgressSuite"

# 上述不认识的框架可以去GIthub搜索查看
end
