# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '美团iPad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 美团iPad

  target '美团iPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '美团iPadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
