# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '美团iPad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 美团iPad

  pod 'MJExtension'
  pod 'SDWebImage'

end
