# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '爱鲜蜂' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 爱鲜蜂

  target '爱鲜蜂Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '爱鲜蜂UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
