# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '优点巴士' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 优点巴士

    pod 'Alamofire'         ##Swift 网络请求
    pod 'Kingfisher'        ##Swift 加载网络图片
    pod 'SnapKit'           ##Swift 约束布局
    pod 'SwiftyJSON'        ##Swift 解析json
    pod 'DGElasticPullToRefresh' ##Swift 刷新框架
    
    
    pod 'SWRevealViewController'
    pod 'MJExtension'
end
