# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '百思不得姐(Swift)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 百思不得姐(Swift)

    pod 'SwiftyJSON', '~> 3.1.3'
    pod 'Alamofire', '~> 4.0'
    pod 'MJRefresh'
    pod 'Kingfisher','~> 3.2.1'
    pod 'PKHUD', '~> 4.0'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'JSPatchPlatform'
    pod 'WeexSDK', '0.6.1'
    pod 'Zhugeio'

end
