# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '爆侃网文' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 0.21.0'
    pod 'YYWebImage', '~> 1.0.3'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDCycleScrollView','~> 1.3'
    pod 'Alamofire', '~> 3.4.0'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'pop', '~> 1.0.9'
    pod 'IQKeyboardManagerSwift'
    pod 'GRMustache.swift', '~> 1.0'
    
    
    
# 主模块(必须)
pod 'ShareSDK3',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'

pod 'MOBFoundation’
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'



# 平台SDK模块(对照一下平台，需要的加上，如果只需要QQ、微信、新浪微博，只需要以下3行)

pod 'ShareSDK3/ShareSDKPlatforms/QQ',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'

# 使用配置文件分享模块（非必需）
pod 'ShareSDK3/ShareSDKConfigurationFile',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'

# 扩展模块（非必需）
pod 'ShareSDK3/ShareSDKExtension',:git => ‘https://git.oschina.net/MobClub/ShareSDK-for-iOS.git'



end
