# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '爆侃网文' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 0.21.0'
    pod 'YYWebImage', '~> 1.0.3'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDCycleScrollView','~> 1.3'
    pod 'Alamofire', '~> 3.4.0'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'pop', '~> 1.0.9'
    pod 'IQKeyboardManagerSwift'
    pod 'GRMustache.swift', '~> 1.0'

end
