# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '斗鱼(OC)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 斗鱼(OC)

  target '斗鱼(OC)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '斗鱼(OC)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
