# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '斗鱼(OC)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 斗鱼(OC)

    pod  'MJRefresh'
    pod  'MJExtension'
    pod  'SDWebImage'
    pod  'Masonry'
    pod  'AFNetworking'

end
