# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ofo(小黄)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ofo(小黄)

  target 'ofo(小黄)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ofo(小黄)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
