# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ofo(小黄)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ofo(小黄)

    pod 'SWRevealViewController'
    pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'AMapNavi'
    pod 'FTIndicator'
    pod 'swiftScan', '~> 1.0.9'
end
