# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '斗鱼' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 斗鱼

  target '斗鱼Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '斗鱼UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
