# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '斗鱼' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 斗鱼
  pod 'Alamofire', '~> 4.2.0'
  pod 'Kingfisher', '~> 3.2.1'
  pod 'SnapKit', '~> 3.0.2'
  pod 'pop', '~> 1.0.9'
end
