# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '百思不得姐(oc)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 百思不得姐(oc)

  target '百思不得姐(oc)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '百思不得姐(oc)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
