# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ReactiveCocoa
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'YYWebImage'
  pod 'ReactiveCocoa', '~> 4.1.0'



end
