# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ReactiveCocoa

    pod 'ReactiveCocoa', '~> 4.1.0'

  target 'ReactiveCocoaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveCocoaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
