# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '快看漫画' do
 pod ’SDWebImage’
 pod ‘MJRefresh’
 pod ‘AFNetworking’
 pod ‘Masonry’
 pod ‘MJExtension’
 pod ‘JGProgressHUD’
 pod ‘UMengAnalytics’
end
