# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '高仿京东' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 高仿京东
  pod 'FMDB'
  pod 'AFNetworking'
  pod 'KINWebBrowser'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'SSKeychain'
end
