# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '斗鱼(Swift)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 斗鱼(Swift)
    pod 'Alamofire', '~> 3.4.0'
    pod 'Kingfisher','~> 2.4.1'
end
