# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '斗鱼(Swift)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 斗鱼(Swift)

  target '斗鱼(Swift)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '斗鱼(Swift)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
