# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '今日头条(Swift)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 今日头条(Swift)

  target '今日头条(Swift)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '今日头条(Swift)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
