# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '今日头条(Swift)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 今日头条(Swift)
  pod 'SnapKit', '~> 0.22.0'
  pod 'Kingfisher', '~> 2.6.1'
  pod "SVProgressHUD"
  pod "FDFullscreenPopGesture", "~> 1.1"
  pod 'Alamofire', '~> 3.5.1'
  pod 'SwiftyJSON', '~> 2.4.0'
  pod "MJRefresh"

end
