# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '京东' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 京东

  target '京东Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '京东UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
