# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'NSObject+Rx'
    pod 'Moya/RxSwift'
    pod 'ObjectMapper'
    pod 'RxDataSources'
    pod 'Then'
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'Reusable'
    pod 'MJRefresh'
    pod 'SVProgressHUD'

  target 'RxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
