# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '今日头条' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 今日头条
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftTheme'

end
