# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '百思不得姐' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod 'Kingfisher'
pod 'MJRefresh'
pod "MJExtension"
pod 'Alamofire'
#pod 'KYCircularProgress'
pod 'SnapKit'

end
