# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '爱鲜蜂' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 爱鲜蜂

    pod 'SVProgressHUD'
    pod 'SDWebImage'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'Masonry'


end
