# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '小日子' do
    
    pod "SVProgressHUD"
    pod "MJRefresh"
    pod "AMap2DMap"
    pod "AMapSearch"
    pod "SDWebImage"
    
    # U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’
    
    # 集成新浪微博
    pod ‘UMengUShare/Social/Sina'
    
    # 集成微信
    pod ‘UMengUShare/Social/WeChat'
    
    # 集成QQ
    pod ‘UMengUShare/Social/QQ'


end
