# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FbMessenger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FbMessenger

  target 'FbMessengerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FbMessengerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
