# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '史上最难的游戏' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 史上最难的游戏

  target '史上最难的游戏Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '史上最难的游戏UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
